@startuml
title: Vista de Componentes

package "InterfaceUI"{
    agent interfaceUISystem.js
}

package "Business logic" {
    agent SystemaMail.jar
    agent secretKeys.env
}

package "Base De Datos"{
    agent dataBase.sql
}

@enduml