@startuml PhysicalView


node "Server" {
  [DataService]
  [BinanceService]
  [RuleEngine]
  [Broker]
  [Notifier]
}


[DataService] --> [BinanceService]
[BinanceService] --> [Binance Socket]
[RuleEngine] --> [DataService]
[RuleEngine] --> [Broker]
[Broker] --> [Binance Api]
[Broker] --> [Notifier]
[Notifier] --> [Discord Api]

@enduml